services:
  - type: static
    name: campus-connect
    env: static
    buildCommand: npm install && npm run build
    publishDir: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
